INSERT INTO rooms(code, name, description, image_url, price) VALUES
                                                                 ('DELUXE-001', 'Habitación Deluxe', 'Amplia habitación con vista al mar, cama king size y jacuzzi privado', 'https://example.com/images/deluxe.jpg', 350.00),
                                                                 ('SUITE-101', 'Suite Ejecutiva', 'Suite de lujo con sala de estar separada y escritorio de trabajo', 'https://example.com/images/suite.jpg', 420.50),
                                                                 ('STD-201', 'Habitación Estándar', 'Cómoda habitación con cama queen size y vista al jardín', 'https://example.com/images/standard.jpg', 180.00),
                                                                 ('FAM-301', 'Suite Familiar', 'Amplio espacio para familias con dos habitaciones separadas', 'https://example.com/images/family.jpg', 320.75),
                                                                 ('ECO-401', 'Habitación Económica', 'Habitación básica pero confortable para viajeros con presupuesto limitado', 'https://example.com/images/economy.jpg', 120.00),
                                                                 ('PENT-501', 'Penthouse', 'Exclusivo penthouse con terraza privada y vista panorámica de 360°', 'https://example.com/images/penthouse.jpg', 750.00),
                                                                 ('JUN-601', 'Suite Junior', 'Suite pequeña pero elegante con área de descanso integrada', 'https://example.com/images/junior.jpg', 275.25),
                                                                 ('HONEY-701', 'Suite Honeymoon', 'Romántica suite para recién casados con detalles especiales', 'https://example.com/images/honeymoon.jpg', 380.00),
                                                                 ('ACC-801', 'Habitación Accesible', 'Habitación adaptada para personas con movilidad reducida', 'https://example.com/images/accessible.jpg', 190.50),
                                                                 ('VIEW-901', 'Habitación con Vista', 'Encantadora habitación con balcón y vistas espectaculares', 'https://example.com/images/view.jpg', 230.00);